import { defineStore } from "pinia";

export interface GameState {
  musicBoxesGames: any[];
  guessingGames: any[];
  singingGames: any[];
  namingGames: any[];
  specialGames: any[];
}

export const useGameStore = defineStore("game", {
  state: (): GameState => ({
    musicBoxesGames: [
      {
        idGame: 2,
        gameName: "Tout un cinéma",
        description: "Reconnaître le film ou la série duquel est tiré l'extrait musical",
        matchesPlayed: [1, 4],
        type: 1,
        position: null,
      },
      {
        idGame: 3,
        gameName: "L'Orchestre symbolique",
        description: "Déchiffrer les symboles pour trouver le titre d'une chanson",
        matchesPlayed: [1, 2, 4],
        type: 1,
        position: null,
      },
      {
        idGame: 4,
        gameName: "Perdu dans les ondes",
        description: "Identifier une chanson à partir d'un extrait interrompu par des interférences",
        matchesPlayed: [2],
        type: 3,
        position: null,
      },
      {
        idGame: 5,
        gameName: "C'est quoi la toune?",
        description: "Identifier une chanson à partir d'un extrait.",
        matchesPlayed: [1, 2, 3, 4],
        type: 4,
        position: null,
      },
      {
        idGame: 8,
        gameName: "La Chanson oubliée",
        description: "Identifier l'artiste derrière une chanson peu connue",
        matchesPlayed: [1],
        type: 1,
        position: null,
      },
      {
        idGame: 9,
        gameName: "Devine the Sogne",
        description: "Trouver la chanson se cachant derrière des paroles traduites",
        matchesPlayed: [1, 3, 4],
        type: 2,
        position: null,
      },
      {
        idGame: 10,
        gameName: "À ma manière",
        description: "Identifier une chanson réinventée dans un autre style musical instrumental",
        matchesPlayed: [1, 2],
        type: 3,
        position: null,
      },
      {
        idGame: 12,
        gameName: "L'Audio visuel",
        description: "Reconnaître la chanson à partir de son vidéoclip joué dans le désordre et sans son",
        matchesPlayed: [1, 3],
        type: 1,
        position: null,
      },
      {
        idGame: 13,
        gameName: "Le Moulin à paroles",
        description: "Identifier une chanson à partir de mots tirés de ses paroles (trois mots d'abord, puis trois autres, jusqu'à quinze)",
        matchesPlayed: [1],
        type: 2,
        position: null,
      },
      {
        idGame: 14,
        gameName: "Radio pirate",
        description: "Identifier une chanson à partir d'un extrait traffiqué (accéléré, à l'envers, etc.)",
        matchesPlayed: [1, 3, 4],
        type: 3,
        position: null,
      },
      {
        idGame: 17,
        gameName: "C'est quoi donc?",
        description: "Identifier une chanson dont le titre ne se trouve pas dans ses paroles",
        matchesPlayed: [2],
        type: 1,
        position: null,
      },
      {
        idGame: 18,
        gameName: "C'est une belle histoire",
        description: "Trouver la chanson à partir d'une histoire résumant le propos de la chanson",
        matchesPlayed: [1, 2],
        type: 2,
        position: null,
      },
      {
        idGame: 19,
        gameName: "Le Mash-Up",
        description: "Identifier les deux chansons qui ont été mélangées ensemble",
        matchesPlayed: [1, 3],
        type: 3,
        position: null,
      },
      {
        idGame: 22,
        gameName: "La Dictée trouée",
        description: "Compléter les paroles d'une chanson",
        matchesPlayed: [1, 2, 4],
        type: 2,
        position: null,
      },
      {
        idGame: 23,
        gameName: "Décomposition",
        description: "Identifier une chanson à partir d'un extrait auquel les instruments s'ajoutent progressivement",
        matchesPlayed: [1, 2, 4],
        type: 3,
        position: null,
      },
      {
        idGame: 25,
        gameName: "Quoiraoké",
        description: "Identifier une chanson à partir de son karaoké muet",
        matchesPlayed: [3],
        type: 2,
        position: null,
      },
      {
        idGame: 27,
        gameName: "Le Bon Sens du terme",
        description: "Trouver la chanson se cachant derrière des paroles dont chaque mot a été remplacé par son synonyme",
        matchesPlayed: [3],
        type: 2,
        position: null,
      },
      {
        idGame: 28,
        gameName: "Une grande inspiration",
        description: "Identifier la chanson originale à partir d'une chanson l'ayant utilisée comme échantillon (sample)",
        matchesPlayed: [2, 4],
        type: 3,
        position: null,
      },
      {
        idGame: 30,
        gameName: "Le 6 à 6",
        description: "Trouver une année à partir de six extraits des plus grands succès de cette année-là",
        matchesPlayed: [2],
        type: 1,
        position: null,
      },
      {
        idGame: 31,
        gameName: "Uno Secondo",
        description: "Identifier une chanson à partir d'un extrait d'une seule seconde",
        matchesPlayed: [2, 4],
        type: 1,
        position: null,
      },
      {
        idGame: 32,
        gameName: "Entre guillemets",
        description: "Identifier un artiste à partir de paroles qu'il a déjà chantées",
        matchesPlayed: [4],
        type: 2,
        position: null,
      },
      {
        idGame: 33,
        gameName: "Le Visage à deux faces",
        description: "Trouver en quel artiste se transforme le visage d'un autre artiste",
        matchesPlayed: [2, 3],
        type: 1,
        position: null,
      },
      {
        idGame: 37,
        gameName: "Mon premier mot",
        description: "Identifier une chanson à partir d'un extrait d'un seul mot de la chanson",
        matchesPlayed: [3],
        type: 1,
        position: null,
      },
      {
        idGame: 38,
        gameName: "Les Duos improbables",
        description: "Trouver les duos ayant réellement collaboré sur une chanson",
        matchesPlayed: [3, 4],
        type: 1,
        position: null,
      },
      {
        idGame: 39,
        gameName: "À qui la toune?",
        description: "Identifier l'artiste d'une chanson à partir d'un extrait",
        matchesPlayed: [3, 4],
        type: 4,
        position: null,
      },
      {
        idGame: 40,
        gameName: "L'Autre Voix",
        description: "Identifier une chanson à partir d'un extrait d'une reprise (cover) de celle-ci",
        matchesPlayed: [3],
        type: 3,
        position: null,
      },
      {
        idGame: 41,
        gameName: "Méli-mélodie",
        description: "Identifier une chanson à partir d'extraits mélangés",
        matchesPlayed: [3],
        type: 3,
        position: null,
      },
      {
        idGame: 42,
        gameName: "Le spectacle doit continuer",
        description: "Identifier une chanson à partir d'un extrait d'une représentation live de celle-ci, joué sans son",
        matchesPlayed: [4],
        type: 1,
        position: null,
      },
      {
        idGame: 43,
        gameName: "La musique à boîte",
        description: "Identifier une chanson à partir de son remix",
        matchesPlayed: [4],
        type: 3,
        position: null,
      },
      {
        idGame: 44,
        gameName: "Intention alternative",
        description: "Identifier une chanson à partir d'une réinterprétation générée par intelligence artificielle",
        matchesPlayed: [4],
        type: 3,
        position: null,
      },
      {
        idGame: 45,
        gameName: "Des titres et des lettres",
        description: "Reconnaître le titre dont les lettres apparaissent progressivement",
        matchesPlayed: [4],
        type: 2,
        position: null,
      },
      {
        idGame: 46,
        gameName: "À contre-sens",
        description: "Trouver la chanson se cachant derrière les paroles dont chaque mot a été remplacé par son contraire",
        matchesPlayed: [4],
        type: 2,
        position: null,
      },
    ],
    guessingGames: [
      {
        idGame: 7,
        gameName: "Do Ré Mime",
        description: "Description du jeu",
        matchesPlayed: [1],
        position: null,
      },
      {
        idGame: 15,
        gameName: "Dans le style de",
        description: "Description du jeu",
        matchesPlayed: [2, 4],
        position: null,
      },
      {
        idGame: 35,
        gameName: "Sur le bord des lèvres",
        description: "Description du jeu",
        matchesPlayed: [3],
        position: null,
      },
    ],
    singingGames: [
      {
        idGame: 11,
        gameName: "Le Stagiaire",
        description: "Description du jeu",
        matchesPlayed: [2],
        position: null,
      },
      {
        idGame: 21,
        gameName: "L'Audition à l'aveugle",
        description: "Description du jeu",
        matchesPlayed: [3],
        position: null,
      },
      {
        idGame: 48,
        gameName: "Qu'est-ce que tu me chantes?",
        description: "Description du jeu",
        matchesPlayed: [4],
        position: null,
      },
    ],
    namingGames: [
      {
        idGame: 16,
        gameName: "Les Noms communs",
        description: "Description du jeu",
        matchesPlayed: [1],
        position: null,
      },
      {
        idGame: 26,
        gameName: "Le Bras de fer",
        description: "Description du jeu",
        matchesPlayed: [2],
        position: null,
      },
      {
        idGame: 36,
        gameName: "D'un mot à l'autre",
        description: "Description du jeu",
        matchesPlayed: [3],
        position: null,
      },
      {
        idGame: 47,
        gameName: "La Basse Note",
        description: "Description du jeu",
        matchesPlayed: [4],
        position: null,
      },
    ],
    specialGames: [
      {
        idGame: 20,
        gameName: "La Lecture musicale",
        description: "Description du jeu",
        matchesPlayed: [1],
        position: null,
      },
      {
        idGame: 29,
        gameName: "Genre style comme",
        description: "Description du jeu",
        matchesPlayed: [2, 3],
        position: null,
      },
      {
        idGame: 49,
        gameName: "Le Roi de la montagne",
        description: "Description du jeu",
        matchesPlayed: [4],
        position: null,
      },
    ],
  }),
  getters: {},
  actions: {},
});
